# NumPy Basic

**1. Write a Numpy program to get the Numpy version and show the Numpy build configuration.**

In [2]:
# `numpy.__version__` & `numpy.show_config()`
import numpy as np

print(np.__version__)
print(np.show_config())

1.23.3
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

**2. Write a NumPy program to get help with the add function.**

In [3]:
# `numpy.info()`
import numpy as np

print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**3. Write a NumPy program to test whether none of the elements of a given array are zero.**

In [6]:
# [1] `numpy.all()`
# `numpy.all(x)` will simply call `x.all()` if `x` is a `numpy.ndarray` 
# `numpy.all(x)` will convert `x` into a `numpy.ndarray` and then call `x.all()` if `x` is not a `numpy.ndarray`
import numpy as np

x = np.array([1, 2, 3, 4])
print("Original array:", x)
print("Test if none of the elements of the said array is zero:", np.all(x))

x = np.array([0, 1, 2, 3])
print("Original array:", x)
print("Test if none of the elements of the said array is zero:", np.all(x))

Original array: [1 2 3 4]
Test if none of the elements of the said array is zero: True
Original array: [0 1 2 3]
Test if none of the elements of the said array is zero: False


In [10]:
# [2] `numpy.ndarray.all()`
# `numpy.ndarray.all()` is a method of `numpy.ndarray` object; call this directly will be faster than `numpy.all()`
import numpy as np

x = np.array([1, 2, 3, 4])
print("Original array:", x)
print("Test if none of the elements of the said array is zero:", x.all())

x = np.array([0, 1, 2, 3])
print("Original array:", x)
print("Test if none of the elements of the said array is zero:", x.all())

Original array: [1 2 3 4]
Test if none of the elements of the said array is zero: True
Original array: [0 1 2 3]
Test if none of the elements of the said array is zero: False


In [8]:
# [3] `all()`
# `all()` works on any iterable
import numpy as np

x = np.array([1, 2, 3, 4])
print("Original array:", x)
print("Test if none of the elements of the said array is zero:", all(x))

x = np.array([0, 1, 2, 3])
print("Original array:", x)
print("Test if none of the elements of the said array is zero:", all(x))

Original array: [1 2 3 4]
Test if none of the elements of the said array is zero: True
Original array: [0 1 2 3]
Test if none of the elements of the said array is zero: False


**4. Write a NumPy program to test if any of the elements of a given array are non-zero.**

In [11]:
# [1] `numpy.any()`
import numpy as np

x = np.array([1, 0, 0, 0])
print("Original array:", x)
print("Test if any of the elements of the said array is non-zero:", np.any(x))

x = np.array([0, 0, 0, 0])
print("Original array:", x)
print("Test if any of the elements of the said array is non-zero:", np.any(x))

Original array: [1 0 0 0]
Test if none of the elements of the said array is zero: True
Original array: [0 0 0 0]
Test if none of the elements of the said array is zero: False


In [12]:
# [2] `numpy.ndarray.any()`
import numpy as np

x = np.array([1, 0, 0, 0])
print("Original array:", x)
print("Test if none of the elements of the said array is zero:", x.any())

x = np.array([0, 0, 0, 0])
print("Original array:", x)
print("Test if none of the elements of the said array is zero:", x.any())

Original array: [1 0 0 0]
Test if none of the elements of the said array is zero: True
Original array: [0 0 0 0]
Test if none of the elements of the said array is zero: False


**5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).**

In [13]:
# `numpy.isfinite()`
import numpy as np

a = np.array([1, 0, np.nan, np.inf])

print("Original array:", a)
print("Test a given array element-wise for finiteness:", np.isfinite(a))

Original array: [ 1.  0. nan inf]
Test a given array element-wise for finiteness: [ True  True False False]


**6. Write a NumPy program to test elements-wise for positive or negative infinity.**

In [14]:
# `numpy.isinf()`
import numpy as np

a = np.array([1, 0, np.nan, np.inf])

print("Original array:", a)
print("Test a given array element-wise for positive or negative infinity:", np.isinf(a))

Original array: [ 1.  0. nan inf]
Test a given array element-wise for positive or negative infinity: [False False False  True]


**7. Write a NumPy program to test element-wise for NaN of a given array.**

In [15]:
# `numpy.isnan()`
import numpy as np

a = np.array([1, 0, np.nan, np.inf])

print("Original array:", a)
print("Test a given array element-wise for positive or negative infinity:", np.isnan(a))

Original array: [ 1.  0. nan inf]
Test a given array element-wise for positive or negative infinity: [False False  True False]


**8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not.**

In [16]:
# `numpy.iscomplex()` & `numpy.isreal()` & `numpy.isscalar()`
import numpy as np

a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])

print("Original array:", a)
print("Check for complex number:", np.iscomplex(a))
print("Check for real number:", np.isreal(a))

print("Check for scalar type:", np.isscalar(3.6))
print("Check for scalar type:", np.isscalar([3.6]))

Original array: [1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Check for complex number: [ True False False False False  True]
Check for real number: [False  True  True  True  True False]
Check for scalar type: True
Check for scalar type: False


**9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.**

In [17]:
# `np.allclose()`
# absolute(a - b) <= (atol + rtol * absolute(b))
# Default absolute tolerance `atol = 1e-08`
# Default relative tolerance `rtol = 1e-05`
import numpy as np

print("Test if two arrays are element-wise equal within a tolerance:")
# absolute(a - b) = [1e5 0.9e-7]
# atol + rtol * absolute(b) = [1e-8 + 1.00001e5   1e-8 + 1e-13]
print(np.allclose([1e10, 1e-7], [1.00001e10, 1e-8]))
# absolute(a - b) = [1e5 0.9e-8]
# atol + rtol * absolute(b) = [1e-8 + 1.00001e5   1e-8 + 1e-14]
print(np.allclose([1e10, 1e-8], [1.00001e10, 1e-9]))
# absolute(a - b) = [1e6 0.9e-8]
# atol + rtol * absolute(b) = [1e-8 + 1.0001e5   1e-8 + 1e-14]
print(np.allclose([1e10, 1e-8], [1.0001e10, 1e-9]))

# `equal_nan=False`: Whether to compare NaN’s as equal
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


**10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.**

In [20]:
# `numpy.greater()` & `numpy.greater_equal()` & `numpy.less()` & `numpy.less_equal()`
import numpy as np

x = np.array([3, 5])
y = np.array([2, 5])

print("Original array:", x, y)
print("Comparison - greater:", np.greater(x, y))
print("Comparison - greater_equal:", np.greater_equal(x, y))
print("Comparison - less:", np.less(x, y))
print("Comparison - less_equal:", np.less_equal(x, y))

Original array: [3 5] [2 5]
Comparison - greater: [ True False]
Comparison - greater_equal: [ True  True]
Comparison - less: [False False]
Comparison - less_equal: [False  True]


**11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.**

In [21]:
# `numpy.equal()` & `numpy.isclose()`
# Formula & parameters' default values of `isclose()` are the same as `allclose()`
import numpy as np

x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

print("Original array:", x, y)
print("Comparison - equal:", np.equal(x, y))
print("Comparison - equal within a tolerance:", np.isclose(x, y))

Original array: [  72   79   85   90  150 -135  120  -10   60  100] [  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - equal: [ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance: [ True  True  True  True  True  True  True  True  True  True]


**12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.**

In [31]:
# [1] `numpy.ndarray.size` & `numpy.ndarray.itemsize`
# `numpy.ndarray` does not correctly support `sys.getsizeof()`
# import sys
import numpy as np

a = np.array([1, 7, 13, 105])

# print("%d bytes" % sys.getsizeof(a))
# 144 bytes
# print("%d bytes" % sys.getsizeof([1, 7, 13, 105]))
# 88 bytes

print("Original array:", a)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (a.size * a.itemsize))

Original array: [  1   7  13 105]
Size of the memory occupied by the said array:
32 bytes


In [32]:
# [2] `numpy.ndarray.nbytes`
import numpy as np

a = np.array([1, 7, 13, 105])

print("Original array:", a)
print("Size of the memory occupied by the said array:")
print("%d bytes" % a.nbytes)

Original array: [  1   7  13 105]
Size of the memory occupied by the said array:
32 bytes


**13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.**

In [34]:
# [1] Created from python list
import numpy as np

a = np.array([0] * 10)
b = np.array([1] * 10)
c = np.array([5] * 10)

print("An array of 10 zeros:", a)
print("An array of 10 ones:", b)
print("An array of 10 fives:", c)

An array of 10 zeros: [0 0 0 0 0 0 0 0 0 0]
An array of 10 ones: [1 1 1 1 1 1 1 1 1 1]
An array of 10 fives: [5 5 5 5 5 5 5 5 5 5]


In [35]:
# [2] `numpy.zeros()` & `numpy.ones()`
import numpy as np

a = np.zeros(10)
b = np.ones(10)
c = np.ones(10) * 5

print("An array of 10 zeros:", a)
print("An array of 10 ones:", b)
print("An array of 10 fives:", c)

An array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**14. Write a NumPy program to create an array of integers from 30 to 70.**

In [39]:
# [1] Created from python list
import numpy as np

a = np.array(range(30, 71))

print("Array of the integers from 30 to 70:", a)

Array of the integers from 30 to 70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [40]:
# [2] `numpy.arange()`
import numpy as np

a = np.arange(30, 71)

print("Array of the integers from 30 to 70:", a)

Array of the integers from 30 to 70: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


**15.Write a NumPy program to create an array of all even integers from 30 to 70.**

In [41]:
# `numpy.arange()`
import numpy as np

a = np.arange(30, 71, 2)

print("Array of all even integers from 30 to 70:", a)

Array of all even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


**16. Write a NumPy program to create a 3x3 identity matrix.**

In [45]:
# [1] `numpy.eye()`
import numpy as np

i = np.eye(3)

print("3x3 identity matrix:")
print(i)

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
# [2] `numpy.identity()`
# `numpy.identity()` just calls `numpy.eye()`
import numpy as np

i = np.identity(3)

print("3x3 identity matrix:")
print(i)

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**17. Write a NumPy program to generate a random number between 0 and 1.**

In [56]:
# `numpy.random.random()`
import numpy as np

# Only one parameter `size=None`
rand_num = np.random.random()

print("Random number between 0 and 1:", rand_num)

Random number between 0 and 1: 0.5591832669244536


**18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.**

In [54]:
# `numpy.random.normal()`
import numpy as np

# Parameters: (loc=0.0, scale=1.0, size=None)
rand_nums = np.random.normal(0, 1, 15)

print("15 random numbers from a standard normal distribution:")
print(rand_nums)

15 random numbers from a standard normal distribution:
[ 0.16375144 -1.2807765  -1.58258736  1.54402651 -0.21703082  0.74398403
  0.64846866  0.50264273 -1.23046157 -1.04332306 -0.05530968 -0.07968339
 -0.35770947 -0.80559923  0.26791261]


**19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.**

In [60]:
# Array slicing & `numpy.arange()`
import numpy as np

a = np.arange(15, 56)

print("Original vector:")
print(a)
print("All values except the first and last of the said vector:")
print(a[1:-1])

Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


**20. Write a NumPy program to create a 3X4 array and iterate over it.**

In [62]:
# [1] `numpy.ndarray.reshape()` & `numpy.nditer()`
import numpy as np

a = np.random.normal(0, 1, 12).reshape(3, 4)

print("Original array:")
print(a)
print("Each element of the array is:")
for i in np.nditer(a):
    print(i, end=" ")

Original array:
[[ 1.72897514 -0.23554043  0.96985204  1.6230506 ]
 [ 0.87119946 -0.85694914 -0.18818517 -0.24059022]
 [ 0.07827248 -0.89701456 -0.79509289 -1.88005207]]
Each element of the array is:
1.7289751442558243 -0.23554042881699 0.9698520350418939 1.6230506006905572 0.8711994593942077 -0.8569491357218127 -0.18818517121050268 -0.2405902216357698 0.07827248053168133 -0.8970145640367856 -0.7950928919520506 -1.8800520657004234 

In [63]:
# [2] `numpy.random.normal(size)` & `numpy.nditer()`
import numpy as np

a = np.random.normal(0, 1, (3, 4))

print("Original array:")
print(a)
print("Each element of the array is:")
for i in np.nditer(a):
    print(i, end=" ")

Original array:
[[-0.65454929 -0.54883507 -0.08898847  1.46358022]
 [-1.02203243  0.41032939  0.94619518  1.26850746]
 [-0.11935359 -2.5372944  -0.48486769  1.06117952]]
Each element of the array is:
-0.6545492888408706 -0.5488350664786932 -0.0889884681986829 1.4635802231453932 -1.02203243188969 0.4103293892105104 0.9461951764927715 1.2685074587512128 -0.11935358533600052 -2.5372944039454195 -0.4848676880386649 1.0611795235065997 

**21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.**

In [65]:
# `numpy.linspace`
import numpy as np

# Parameters: (start, stop, num=50)
v = np.linspace(5, 50, 10)

print("Length 10 with values evenly distributed between 5 and 50:")
print(v)

Length 10 with values evenly distributed between 5 and 50:
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


**22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.**

In [66]:
# Boolean indexing
import numpy as np

v = np.arange(0, 21)
print("Original vector:")
print(v)

print("After changing the sign of the numbers in the range from 9 to 15:")
v[(v >= 9) & (v <= 15)] *= -1
print(v)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


**23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.**

In [68]:
# `numpy.random.randint()`
import numpy as np

# Parameters: (low, high=None, size=None, dtyle=int)
v = np.random.randint(0, 11, 5)

print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
print(v)

Vector of length 5 filled with arbitrary integers from 0 to 10:
[9 8 1 6 7]


**24. Write a NumPy program to multiply the values of two given vectors.**

In [69]:
# `*`
import numpy as np

x = np.array([100, 8, 3, 16])
y = np.random.randint(0, 100, 4)
result = x * y

print("Vector 1:")
print(x)
print("Vector 2:")
print(y)
print("Multiply the values of two said vectors:")
print(result)

Vector 1:
[100   8   3  16]
Vector 2:
[46 25 45 98]
Multiply the values of two said vectors:
[4600  200  135 1568]


**25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.**

In [71]:
# [1] `numpy.linspace()` & `numpy.ndarray.reshape()`
import numpy as np

a = np.linspace(10, 21, 12).reshape(3, 4)

print(a)

[[10. 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]]


In [72]:
# [2] `numpy.arange()` & `numpy.ndarray.reshape()`
import numpy as np

a = np.arange(10, 22).reshape(3, 4)

print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


**26. Write a NumPy program to find the number of rows and columns in a given matrix.**

In [73]:
# `numpy.ndarray.shape`
import numpy as np

a = np.random.normal(0, 10, (3, 4))

print("Original matrix:")
print(a)
print("Number of rows and columns of the said matrix:")
print(a.shape)

Original matrix:
[[  6.03049415   1.21756075 -19.21095031   7.04610167]
 [ -4.39607628  -9.91241626   8.83225343  -8.72568766]
 [ -6.16683926   3.13079209  -6.07638288 -15.47648333]]
Number of rows and columns of the said matrix:
(3, 4)


**27. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.**

In [74]:
# `numpy.eye()` or `numpy.identity()`
import numpy as np

i = np.eye(3)
# i = np.identity(3)

print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.**

In [75]:
# Array slicing & `numpy.ones(size)`
import numpy as np

a = np.ones((10, 10))
a[1:-1, 1:-1] = 0

print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.**

In [78]:
# for loop & `numpy.zeros()`
import numpy as np

a = np.zeros((5, 5))
for i in range(0, 5):
    a[i, i] = i + 1
    
print(a)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [79]:
# [2] `numpy.diag(v)`
import numpy as np

a = np.diag([1, 2, 3, 4, 5])

print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


**30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.**

In [82]:
# Array slicing & `numpy.zeros()`
import numpy as np

a = np.zeros((4, 4))
# rows 0, 2; columns 1, 3
a[::2, 1::2] = 1
# rows 1, 3; columns 0, 2
a[1::2, ::2] = 1

print(a)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


**31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.**

In [83]:
# `numpy.random.random(size)`
import numpy as np

a = np.random.random((3, 3, 3))

print(a)

[[[0.45376748 0.58773613 0.32980604]
  [0.11413024 0.22825167 0.93587001]
  [0.47616166 0.54254727 0.79557692]]

 [[0.75359548 0.37277045 0.54974256]
  [0.934096   0.24851634 0.34201562]
  [0.10915372 0.66599692 0.42123557]]

 [[0.80983331 0.51493158 0.62629913]
  [0.01686448 0.77066879 0.74304862]
  [0.64710998 0.63563932 0.22271497]]]


**32. Write a NumPy program to compute the sum of all elements, the sum of each column and the sum of each row in a given array.**

In [84]:
# `numpy.sum(a, axis=None)`
import numpy as np

a = np.array([[0, 1], [2, 3]])

print("Original array:")
print(a)
print("Sum of all elements:")
print(np.sum(a))
print("Sum of each column:")
print(np.sum(a, axis=0))
print("Sum of each row:")
print(np.sum(a, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


**33. Write a NumPy program to compute the inner product of two given vectors.**

In [89]:
# [1] `numpy.ndarray.dot()`
import numpy as np

a = np.array([3, 5])
b = np.array([8, 16])

print("Original vectors:")
print(a)
print(b)
print("Inner product of said vectors:")
print(a.dot(b))

Original vectors:
[3 5]
[ 8 16]
Inner product of said vectors:
104


In [88]:
# [2] `numpy.dot(a, b)`
import numpy as np

a = np.array([3, 5])
b = np.array([8, 16])

print("Original vectors:")
print(a)
print(b)
print("Inner product of said vectors:")
print(np.dot(a, b))

Original vectors:
[3 5]
[ 8 16]
Inner product of said vectors:
104


**34. Write a NumPy program to add a vector to each row of a given matrix.**

In [92]:
# [1] `+`
import numpy as np

a = np.arange(0, 12).reshape(3, 4)
v = np.ones((1, 4))
result = a + v

print("Orginal matrix:")
print(a)
print("Vector to add:")
print(v)
print("After adding the vector to each row of the matrix:")
print(result)

Orginal matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Vector to add:
[[1. 1. 1. 1.]]
After adding the vector to each row of the matrix:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [94]:
# [2] for loop & `numpy.empty_like()`
import numpy as np

a = np.arange(0, 12).reshape(3, 4)
v = np.ones((1, 4))
result = np.empty_like(a)

# Loop through columns
for i in range(3):
    result[i, :] = a[i, :] + v
    
print("Orginal matrix:")
print(a)
print("Vector to add:")
print(v)
print("After adding the vector to each row of the matrix:")
print(result)

Orginal matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Vector to add:
[[1. 1. 1. 1.]]
After adding the vector to each row of the matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


**35. Write a NumPy program to save a given array to a binary file.**

In [95]:
# `numpy.save()` & `numpy.load()` & `numpy.array_equal()`
# `.npy` persists a single arbitrary NumPy array
import os
import numpy as np

a = np.arange(10)
np.save("tmp_array.npy", a)

print("Check if \"tmp_array.npy\" exists or not?")
if os.path.exists("tmp_array.npy"):
    x = np.load("tmp_array.npy")
    print(np.array_equal(a, x))

Check if "tmp_array.npy" exists or not?
True


**36. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.**

In [97]:
# `numpy.savez()` & `numpy.load()`
# `.npz` is a uncompressed zipped archive of files named after the variables they contain
import numpy as np

a = np.arange(1, 11)
b = np.arange(11, 20)
np.savez("tmp_array.npz", a=a, b=b)

print("Orignal arrays:")
print(a)
print(b)

print("Load arrays from the \"temp_arra.npz\" file:")
with np.load("tmp_array.npz") as data:
    x = data["a"]
    y = data["b"]
    print(x)
    print(y)

Orignal arrays:
[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
Load arrays from the "temp_arra.npz" file:
[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
